# -*- coding: utf-8 -*-
"""Q3.ipynb

Automatically generated by Colaboratory.

Original file is located at
    https://colab.research.google.com/drive/1nkBBQrSPBWN3G5q_LOPkKWOlrw4oxGe_
"""

import numpy as np
import matplotlib.pyplot as plt
from scipy.stats import multivariate_normal

x, y = np.mgrid[-2:4:.001, -2:4:.001]
z = multivariate_normal([1, 1], [[1, 0],[0, 2]]).pdf(np.dstack((x, y)))
fig, ax = plt.subplots(1,1)
cp = plt.contourf(x, y, z)
plt.title('Plot for Part 1')
fig.colorbar(cp)
plt.show()

x, y = np.mgrid[-4:2:.001, -3:7:.001]
z = multivariate_normal([-1, 2], [[2, 1],[1, 4]]).pdf(np.dstack((x, y)))
fig, ax = plt.subplots(1,1)
cp = plt.contourf(x, y, z)
plt.title('Plot for Part 2')
fig.colorbar(cp)
plt.show()

x, y = np.mgrid[-3:5:.001, -2:4:.001]
mu_1 = [0, 2]
mu_2 = [2, 0]
cov = [[2,1],[1,1]]
z_1 = multivariate_normal(mu_1, cov).pdf(np.dstack((x, y)))
z_2 = multivariate_normal(mu_2, cov).pdf(np.dstack((x, y)))
z = z_1 - z_2
fig, ax = plt.subplots(1,1)
cp = plt.contourf(x, y, z)
plt.title('Plot for Part 3')
fig.colorbar(cp)
plt.show()

x, y = np.mgrid[-5:5:.001, -3:5.5:.001]
mu_1 = [0, 2]
mu_2 = [2, 0]
cov_1 = [[2,1],[1,1]]
cov_2 = [[2,1],[1,4]]
z_1 = multivariate_normal(mu_1, cov_1).pdf(np.dstack((x, y)))
z_2 = multivariate_normal(mu_2, cov_2).pdf(np.dstack((x, y)))
z = z_1 - z_2
fig, ax = plt.subplots(1,1)
cp = plt.contourf(x, y, z)
plt.title('Plot for Part 4')
fig.colorbar(cp)
plt.show()

x, y = np.mgrid[-4:5:.001, -4:4:.001]
mu_1 = [1, 1]
mu_2 = [-1, -1]
cov_1 = [[2,0],[0,1]]
cov_2 = [[2,1],[1,2]]
z_1 = multivariate_normal(mu_1, cov_1).pdf(np.dstack((x, y)))
z_2 = multivariate_normal(mu_2, cov_2).pdf(np.dstack((x, y)))
z = z_1 - z_2
fig, ax = plt.subplots(1,1)
cp = plt.contourf(x, y, z)
plt.title('Plot for Part 5')
fig.colorbar(cp)
plt.show()

